module.exports = {
  alps: require("./alps"),
  button: require("./button"),
  choc: require("./choc"),
  chocmini: require("./chocmini"),
  diode: require("./diode"),
  jstph: require("./jstph"),
  jumper: require("./jumper"),
  mx: require("./mx"),
  oled: require("./oled"),
  omron: require("./omron"),
  pad: require("./pad"),
  promicro: require("./promicro"),
  promicro_pretty: require("./promicro_pretty"),
  promicro_pretty_no_traces: require("./promicro_pretty_no_traces"),
  rgb: require("./rgb"),
  rotary: require("./rotary"),
  scrollwheel: require("./scrollwheel"),
  slider: require("./slider"),
  trrs: require("./trrs"),
  via: require("./via"),
  pcm12: require("./pcm12"),
  bat: require("./bat"),
  b3u1000p: require("./b3u1000p"),
};
